### ISSUE TITLE
an issue in "Change opencv, opencv_contrib(optional) to 3.1 version"

### ISSUE THREAD

**Issue by weggy999** [chaos5958/Install-Caffe-ssd-on-Jetson-TX2#1]
Hi,

I found an issue in "git cherry-pick 0545d4655fb7ae02f8d4eb1866168e391c87463f". It seems that the commit hash does not exist. Thanks for sharing the instruction.

**Comment by chaos5958** [comment]
Thanks for comment. 
I fixed the wrong commit number. 
Try it again, and, if you have any problems, feel free to ask me. 

-Hyunho Yeo
